### ISSUE TITLE
/users displayed on home page even if user does not have access to tab

### ISSUE THREAD

**Issue by Miguel619** [jdwillmsen/usersrole#39]
Hey Jake! I was checking out your application and noticed the home page has a `/home` hyperlink that leads no where
![image](https://github.com/jdwillmsen/usersrole/assets/66089524/fce83a3d-cd2c-4918-83a8-bef14744127b)
I suggest only displaying this only if the user has access.

Cheers!

**Comment by jdwillmsen** [comment]
I suppose I could make that change to only show the links that the users has access to. Currently when a users tries to access a link they don't have authorization for they are routed to the home page. I do have a ticket to refactor the home page and could make it so that it only shows links the user has access to. Another option is to add an unauthorized page.

**Comment by jdwillmsen** [comment]
This has been addressed and is currently in develop awaiting next release.
